input.onPinPressed(TouchPin.P2, function () {
    music.playMelody("A F E F D G E F ", 300)
    music.playMelody("C5 G B A F A C5 B ", 300)
    music.playMelody("E D G F B A C5 B ", 300)
    music.playMelody("C5 A B G A F G E ", 300)
    music.playMelody("E B C5 A B G A F ", 300)
    music.playTone(330, music.beat(BeatFraction.Breve))
})
input.onPinPressed(TouchPin.P1, function () {
    music.playMelody("E D G F B A C5 B ", 450)
    music.playMelody("A F E F D G E F ", 450)
    music.playMelody("G B A G C5 B A B ", 450)
    music.playMelody("B A G A G F A C5 ", 450)
    music.playMelody("G F G A - F E D ", 450)
    music.playMelody("E C G F B A C5 B ", 450)
    music.playMelody("A G E F D G E F ", 450)
    music.playMelody("G F A G C5 B A B ", 450)
    music.playMelody("B A F A G F A C5 ", 450)
    music.playMelody("G F G F A F E D ", 450)
    music.playTone(262, music.beat(BeatFraction.Breve))
})
